server:
  port: 8081
spring:
  application:
    name: "ApplicationService"
  devtools:
    add-properties: false
  flyway:
    enabled: true
    url: "jdbc:mysql://localhost:3295/crediya_applications"
    user: "root"
    password: "root"
    locations: "classpath:db/migration"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: /webjars
adapters:
  r2dbc:
    host: "localhost"
    port: 3295
    database: "crediya_applications"
    schema: "crediya_applications"
    username: "root"
    password: "root"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
jwt:
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyfjjsm7fr6ZGPCPIgPqT/hQ51UIed4L9vPkeYUpfhU4vXSLjzAOOZy3k0qtYuFqT5WpmvOEf6fsUcvM5vOkjcRYwyiXok3B0JOlNwi5IA+UO2Dh0y2ZWNlw1qUxRyXZDuK/cqXEYx1Kpthx+ZIiVp/qzIXfxbFiZgSdjwPRheYKwlhWM6kpZs5UUwo9fVzRq9vk3xpECJ+7fvbZ3Bg3SoSJ3epxhCALrDf78iCr8go+R9RIiD2bWPd3/I0mPain4yuBhU7kCQuIH50UqhoL5S4lEjwH/D3Jjm69mi6SISWjQuJR+Et6VoMRsfWcouriovJFcCKOmBcBB6OFxPStOKQIDAQAB"
  expiration: 86400000
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  auth-service:
    timeout: 5000
    url: "http://localhost:8080"
logging:
  level:
    co.com.crediya: INFO
    org.springframework.web: INFO

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
