server:
  port: 8081
spring:
  application:
    name: "ApplicationService"
  devtools:
    add-properties: false
  flyway:
    enabled: "${FLYWAY_ENABLED:true}"
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:crediya_applications}"
    user: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    locations: "${FLYWAY_LOCATIONS:classpath:db/migration}"
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
  webjars:
    prefix: "/webjars"
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:3306}"
    database: "${DB_NAME:crediya_applications}"
    schema: "${DB_SCHEMA:crediya_applications}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
jwt:
  public-key: "${JWT_PUBLIC_KEY}"
  expiration: 86400000
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}"
adapter:
  auth-service:
    timeout: "${AUTH_SERVICE_TIMEOUT:5000}"
    url: "${AUTH_SERVICE_URL:http://localhost:8080}"
  sqs:
    region: "us-east-1"
    queueUrl: "http://localhost:4566/000000000000/sample"
    endpoint: "http://localhost:4566 # For localstack only"
logging:
  level:
    co.com.crediya: "INFO"
    org.springframework.web: "INFO"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
